<?= $this->partial('common/header.phtml', $this) ?>
<h3>最新使用者</h3>
<div class="row">
<?php foreach (User::search(1)->order('id DESC')->limit(100) as $user) { ?>
<?php $data = $user->getData(); ?>
<div class="card col-2">
    <?php if ($data->avatar) { ?>
    <div class="ratio ratio-1x1 card-img-top">
        <img style="object-fit: cover;" src="<?= $this->escape($data->avatar) ?>">
    </div>
    <?php } ?>
    <div class="card-body">
        <a href="/<?= urlencode($user->name) ?>">
            <h3 class="card-title"><?= $this->escape($data->info->name) ?></h3>
            <p>@<?= $this->escape($user->name) ?></p>
        </a>
        <p><?= $this->escape($data->info->keyword) ?></p>
        <p><?= $this->escape($data->info->intro) ?></p>
    </div>
</div>
<?php } ?>
</div>
<?= $this->partial('common/footer.phtml', $this) ?>
