<?php
$this->title = sprintf("[ %s ] %s", $this->service->getData()->name, $this->badge->brief);
$records = ServiceBadge::getBadgeList($this->service->id, $this->badge->badge_hash);
foreach (array_slice($records, 1, 5) as $idx => $record) {
    $terms[] = sprintf("%d %s", $idx + 1, $record->name);
}
$this->description = implode("\n", $terms);

?>
<?= $this->partial('common/header.phtml', $this) ?>
<h3>[ <?= $this->escape($this->service->getData()->name) ?> ] <?= $this->escape($this->badge->brief) ?></h3>
<table class="table">
    <thead>
        <tr>
            <th>排名</th>
            <th>時間</th>
            <th>使用者</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($records as $record) { ?>
    <tr>
        <td id="rank-<?= $record->rank ?>"><?= $record->rank ?></td>
        <td><?= date('Y-m-d', $record->badge_time) ?></td>
        <td>
            <?php if (!$this->service->getData()->public) { ?>
            <?php if ($record->user_id and $u = User::find_by_name($record->user_id) and $u->isServiceUserPublic($record->service_user_id)) { ?>
                <a href="/<?= urlencode($record->user_id) ?>"><?= $this->escape($record->name) ?></a>
                <?php } else { ?>
                未公開
                <?php } ?>
            <?php } else { ?>
                <?php if ($record->user_id) { ?>
                <a href="/<?= urlencode($record->user_id) ?>"><?= $this->escape($record->name) ?></a>
                <?php } else { ?>
                <?= $this->escape($record->name) ?>
                <?php } ?>
            <?php } ?>
        </td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<?= $this->partial('common/footer.phtml', $this) ?>
