<?php
$data = $this->user->getData();
$info = $data->info;

?>
<?= $this->partial('common/header.phtml', $this) ?>
<h1>編輯我的個人資料</h1>
<h2>頭像編輯</h2>
<?php if ($data->avatar) { ?>
<img width="128" height="128" src="<?= $this->escape($data->avatar) ?>">
<?php } ?>
<ul>
    <li><a href="/_/user/slacklogin?next=/_/user/setavatar">使用 Slack 的頭像</a></li>
    <li><a href="/_/user/googlelogin?next=/_/user/setavatar">使用 Google 的頭像</a></li>
    <li><a href="/_/user/githublogin?next=/_/user/setavatar">使用 Github 的頭像</a></li>
</ul>
<h2>身份編輯</h2>
<ul>
    <?php foreach (json_decode($this->user->ids) as $id) { ?>
    <li><?= $this->escape($id) ?></li>
    <?php } ?>
</ul>
<ul>
    <li><a href="/_/user/slacklogin?next=/_/user/addid">新增 Slack 的身份</a></li>
    <li><a href="/_/user/googlelogin?next=/_/user/addid">新增 Google 的身份</a></li>
    <li><a href="/_/user/githublogin?next=/_/user/addid">新增 Github 的身份</a></li>
</ul>
<h2>個人資料編輯</h2>
<form method="post" action="/_/user/edit?method=info">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    代號：<?= $this->escape($this->user->name) ?><br>
    顯示名稱：<input type="text" name="info[name]" value="<?= $this->escape($info->name) ?>"><br>
    三個關鍵字：<input type="text" name="info[keyword]" value="<?= $this->escape($info->keyword) ?>"><br>
    自我介紹：<textarea name="info[intro]"><?= $this->escape($info->intro) ?></textarea>
    <button type="submit">修改</button>
</form>
<?= $this->partial('common/footer.phtml', $this) ?>
