<?php
$info = json_decode($this->user->data)->info;
?>
<?= $this->partial('common/header.phtml', $this) ?>
<h1>編輯我的個人資料</h1>
<h2>頭像編輯</h2>
<h2>身份編輯</h2>
<h2>個人資料編輯</h2>
<form method="post" action="/_/user/edit?method=info">
    <input type="hidden" name="sToken" value="<?= $this->sToken ?>">
    代號：<?= $this->escape($this->user->name) ?><br>
    顯示名稱：<input type="text" name="info[name]" value="<?= $this->escape($info->name) ?>"><br>
    三個關鍵字：<input type="text" name="info[keyword]" value="<?= $this->escape($info->keyword) ?>"><br>
    自我介紹：<textarea name="info[intro]"><?= $this->escape($info->intro) ?></textarea>
    <button type="submit">修改</button>
</form>
<?= $this->partial('common/footer.phtml', $this) ?>
