<?php
$data = $this->user->getData();
?>
<?= $this->partial('common/header.phtml', $this) ?>
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="card">
                <?php if ($data->avatar) { ?>
                <img class="card-img-top" src="<?= $this->escape($data->avatar) ?>" width="260" height="260">
                <?php } ?>
                <div class="card-body">
                    <h3 class="card-title"><?= $this->escape($data->info->name) ?></h3>
                    <p>@<?= $this->escape($this->user->name) ?></p>
                    <p><?= $this->escape($data->info->keyword) ?></p>
                    <p><?= $this->escape($data->info->intro) ?></p>
                </div>
            </div>
        </div>
        <div class="col-sm-9 col-md-9">
            <?php foreach (ServiceUser::searchByIds(json_decode($this->user->ids)) as $user) { ?>
            <div class="card">
                <div class="card-header">
                    <?php if ($link = $user->getLink()) { ?>
                    <h5 class="card-title"><a href="<?= $this->escape($link) ?>" target="_blank">[ <?= $this->escape($user->service->getData()->name) ?> ] <?= $this->escape($user->getData()->name) ?></a></h5>
                    <?php } else { ?>
                    <h5 class="card-title">[ <?= $this->escape($user->service->getData()->name) ?> ] <?= $this->escape($user->getData()->name) ?></h5>
                    <?php } ?>
                </div>
                <div class="card-body">
                    <div class="row">
                        <?php $ranks = ServiceBadge::getBadgeRank($user->badges) ?>
                        <?php foreach ($user->badges as $badge) { ?>
                        <div class="col-sm-4">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title"><?= $this->escape($badge->brief) ?></h5>
                                    <h6 class="card-subtitle"><?= date('Y-m-d', $badge->badge_time) ?></h6>
                                    <?php $data = $badge->getData() ?>
                                    <?php if (property_exists($data, 'title')) { ?>
<?php $data->title = mb_strimwidth($data->title, 0, 80, '...', 'UTF-8') ?>
                                        <?php if (property_exists($data, 'url')) { ?>
                                        <p>
                                        <a href="<?= $this->escape($data->url) ?>" target="_blank"><?= $this->escape($data->title) ?></a></p>
                                        <?php } else { ?>
                                        <p><?= $this->escape($data->title) ?></p>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                                <div class="card-footer text-end">
                                    <a href="/_/badge/show?service_id=<?= $badge->service_id ?>&hash=<?= $badge->badge_hash ?>#rank-<?= $ranks->{$badge->id}[0] ?>"><?= $ranks->{$badge->id}[0] ?> / <?= $ranks->{$badge->id}[1] ?></a>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
<?= $this->partial('common/footer.phtml', $this) ?>
