<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<title>g0v 成就系統</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css">
<script type="text/javascript">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
<?php } ?>
</script>
</head>
<body class="<?= $this->escape($this->body_class) ?>">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">g0v 成就系統</a>
        </div>
        <ul class="nav navbar-nav">
            <li>
            <a href="/">回首頁</a>
            </li>
            <?php if (!$login_id = Pix_Session::get('login_id')) { ?>
            <li>
            <a href="/_/user/slacklogin">Slack 登入</a>
            </li>
            <?php } else { ?>
            <li>
            <span class="navbar-text">Hi! <?= $this->escape(Pix_Session::get('login_name')) ?></span>
            </li>
            <?php if ($user = User::findByLoginID($login_id)) { ?>
            <li>
            <a href="/<?= urlencode($user->name) ?>">瀏覽我的頁面</a>
            </li>
            <li>
            <a href="/_/user/edit">修改個人頁面</a>
            </li>
            <?php } ?>
            <li>
            <a href="/_/user/logout">登出</a>
            </li>
            <?php } ?>
        </ul>
    </div>
</nav>
<div class="container-fluid">
    <div class="row-fluid">
